/*
*==Description==
*GeoServer is an open source software server written in Java that allows users
*          to share and edit geospatial data.Designed for interoperability,
*          it publishes data from any major spatial data source using open standards.
*
*Being a community-driven project, GeoServer is developed, tested, and supported by
*      a diverse group of individuals and organizations from around the world.
*
*GeoServer is the reference implementation of the Open Geospatial Consortium (OGC)
*          Web Feature Service (WFS) and Web Coverage Service (WCS) standards, as well as
*          a high performance certified compliant Web Map Service (WMS), compliant
*          Catalog Service for the Web (CSW) and implementing Web Processing Service (WPS).
*          GeoServer forms a core component of the Geospatial Web.
*
*==License==
*GeoServer is distributed under the GNU General Public License Version 2.0 license:
*
*    GeoServer, open geospatial information server
*    Copyright (C) 2014-2020 Open Source Geospatial Foundation.
*    Copyright (C) 2001-2014 OpenPlans
*
*    This program is free software; you can redistribute it and/or modify
*    it under the terms of the GNU General Public License as published by
*    the Free Software Foundation; either version 2 of the License, or
*    (at your option) any later version (collectively, "GPL").
*
*    As an exception to the terms of the GPL, you may copy, modify,
*    propagate, and distribute a work formed by combining GeoServer with the
*    EMF and XSD Libraries, or a work derivative of such a combination, even if
*    such copying, modification, propagation, or distribution would otherwise
*    violate the terms of the GPL. Nothing in this exception exempts you from
*    complying with the GPL in all respects for all of the code used other
*    than the EMF and XSD Libraries. You may include this exception and its grant
*    of permissions when you distribute GeoServer.  Inclusion of this notice
*    with such a distribution constitutes a grant of such permissions.  If
*    you do not wish to grant these permissions, remove this paragraph from
*    your distribution. "GeoServer" means the GeoServer software licensed
*    under version 2 or any later version of the GPL, or a work based on such
*    software and licensed under the GPL. "EMF and XSD Libraries" means
*    Eclipse Modeling Framework Project and XML Schema Definition software
*    distributed by the Eclipse Foundation, all licensed
*    under the Eclipse Public License Version 1.0 ("EPL"), or a work based on
*    such software and licensed under the EPL.
*
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU General Public License for more details.
*
*    You should have received a copy of the GNU General Public License
*    along with this program; if not, write to the Free Software
*    Foundation, Inc., 51 Franklin Street, Suite 500, Boston, MA 02110-1335  USA
*
*==More Information==
*Visit the website or read the docs.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.0-hudson-3037-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.07.27 at 11:06:51 PM CDT
//
package org.geoserver.wps.ppio.gpx;

import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the org.geotools.gpx.bean package.
 *
 * <p>An ObjectFactory allows you to programatically construct new instances of the Java
 * representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element
 * declarations and model groups. Factory methods for each of these are provided in this class.
 */
public class ObjectFactory {
    private static final QName _Gpx_QNAME = new QName("http://www.topografix.com/GPX/1/1", "gpx");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes
     * for package: org.geotools.gpx.bean
     */
    public ObjectFactory() {}

    /** Create an instance of {@link CopyrightType } */
    public CopyrightType createCopyrightType() {
        return new CopyrightType();
    }

    /** Create an instance of {@link PtType } */
    public PtType createPtType() {
        return new PtType();
    }

    /** Create an instance of {@link PtsegType } */
    public PtsegType createPtsegType() {
        return new PtsegType();
    }

    /** Create an instance of {@link MetadataType } */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /** Create an instance of {@link EmailType } */
    public EmailType createEmailType() {
        return new EmailType();
    }

    /** Create an instance of {@link TrksegType } */
    public TrksegType createTrksegType() {
        return new TrksegType();
    }

    /** Create an instance of {@link WptType } */
    public WptType createWptType() {
        return new WptType();
    }

    /** Create an instance of {@link LinkType } */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /** Create an instance of {@link TrkType } */
    public TrkType createTrkType() {
        return new TrkType();
    }

    /** Create an instance of {@link PersonType } */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /** Create an instance of {@link GpxType } */
    public GpxType createGpxType() {
        return new GpxType();
    }

    /** Create an instance of {@link BoundsType } */
    public BoundsType createBoundsType() {
        return new BoundsType();
    }

    /** Create an instance of {@link RteType } */
    public RteType createRteType() {
        return new RteType();
    }

    /** Create an instance of {@link ExtensionsType } */
    public ExtensionsType createExtensionsType() {
        return new ExtensionsType();
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link GpxType }{@code >} */
    /*
     * @XmlElementDecl(namespace = "http://www.topografix.com/GPX/1/1", name = "gpx") public JAXBElement<GpxType> createGpx(GpxType value) { return
     * new JAXBElement<GpxType>(_Gpx_QNAME, GpxType.class, null, value); }
     */
}
